### ISSUE TITLE
fix problem with type ArrayList in Team class #2

### ISSUE THREAD

**Issue by kaimex9** [kaimex9/Prac1-Github#2]
![image](https://github.com/user-attachments/assets/bdeaa7c4-b63c-406e-b471-157d78d2780b)

**Comment by pl2023342** [comment]
[Issue.zip](https://github.com/user-attachments/files/17129492/Issue.zip)

**Comment by pl2023342** [comment]
`<?
/**
 * List of players in the team
 *
 * @var array
 */
private $players;
?>`

**Comment by pl2023342** [comment]
[Issue.zip](https://github.com/user-attachments/files/17130380/Issue.zip)
